### ISSUE TITLE
Status of this repository

### ISSUE THREAD

**Issue by paulmasson** [webMath/algesurf#3]
@theo-armour as we both know this repository has many issues induced by moving it into this newer organization that requires HTTPS rather than HTTP. Before I continue fixing these errors let's arrive at some clarity on the future direction.

What would you propose as the best way forward in bringing this repository back to its operational state?

How much of the code will you rewrite? In what time frame?

Should we just begin with a clean repository and deprecate this one?

**Comment by paulmasson** [comment]
@theo-armour ten days is long enough for a response...

**Comment by theo-armour** [comment]
@paulmasson 

> Should we just begin with a clean repository and deprecate this one?

Sorry. I was thinking - from our meatworld meat-up - that this repo was to be deprecated - and I would start fresh - with replacements by the Thanksgiving time frame.

**Comment by paulmasson** [comment]
@theo-armour Thanksgiving is now ten days away. Any plans to work on this?

**Comment by theo-armour** [comment]
@paulmasson 

Yes, soon we must give thanks to the great erdogan in the sky.

The question is whether the the stuffing will have noethers in it or nut.

I'm not sure the best answer. Here are some issues:

The web is replete with web sites made by old men ~~~wearing lycra riding bikes~~~ creating pretty pictures of math equations. Are we here to build yet another such presence? <links to a dozen sites to be added>

Even if we added a set of even better interactions, are we not just creating more pretty pictures? We have not added to the system of classification. Or added anything of significance to the canon.

But more to the point: what is the best way to share our discoveries? We may access a myriad of of equation possibilities - each of which has innumerable coefficient possibilities - of which certain results may tickle certain humans pink. How do we share the capture of the rapture? Do we use MathML? Or a Math Sage Way or JSON or what?

And then even with our canonical classified raptures, how do we get kids to hack the marvelous social capital we create? How do we help incite math gamers and hackers to come into existence?

There are no easy answers to any of these topics, but a goo place to start would be a goo structure - in JSON? - for sharing equations and background on the equations,

**Comment by paulmasson** [comment]
@theo-armour This issue is not about the grand scheme of the organization: it is about returning these pages to basic functionality. You told me in person that you could do that easily by the present time. Are you now saying you have no intention of just fixing the broken stuff while rewriting it more cleanly?

**Comment by paulmasson** [comment]
A timely reply was expected out of common courtesy, even if only to state that nothing will be done any time soon. Apparently the question did not merit common courtesy.

This conversation is no longer productive.

**Comment by paulmasson** [comment]
@theo-armour with the imminent demise of Rawgit, it is time again to ask: are going to return the pages in this repository to basic functionality or not? A simple question, with a simple yes or no answer.

You have said many times in the past that what one writes on the Internet is what that person is. You personally leave behind a great deal of broken code. Is that how you want people to see you? Will that change at the very least with this repository?

**Comment by theo-armour** [comment]
@paulmasson 

Astute observations. Thank you for reopening this issue.

>You have said many times in the past that what one writes on the Internet is what that person is. 
>You personally leave behind a great deal of broken code.

And I also leave behind twenty years of failures - projects that went nowhere.

['Move fast and break things']( https://xkcd.com/1428/ )

But, fingers crossed, I have recently found something worthwhile to do,

* https://www.openstudio.net/contributors &laquo; scroll to bottom

***

> Is that how you want people to see you?

More fun: How I want me to see me. ;-)

In the past, I always thought there would be a time in the future when I would calm down - and deal properly with my legacy.

Now that the future has arrived, I find there's a surfeit of legacy to deal with plus an overabundance of future beckoning. So what is a better way to terminate: 'He ran helter skelter off the deep end' or 'All his commit messages were salient'?

***

> with the imminent demise of Rawgit, 
> it is time again to ask: are going to return the pages in this repository to basic functionality or not? 
> A simple question, with a simple yes or no answer.

The simple answer is no.

The more nuanced response to the Rawgit matter is that future methods for achieving similar results for this and other projects must be put into place. My current look/sees are documented here:

* http://www.ladybug.tools/spider/#pages/content-delivery-network.md  

I expect to arrive at a workable solution in a few weeks.

The more nuanced response regarding the webMath project is that webMath - along with numerous other make-math-more-fun web sites - are the sometimes charming but mostly empty vanities of little old men around the world. Legacies in their own time.

What all these efforts really need are cataloging, curation, standards and metrics to adhere to. They need wrangling, marshaling and marketing. In other words, they have to be based on standard math tools similar to [Arduino]( https://en.wikipedia.org/wiki/Arduino ) and [Raspberry Pi]( https://en.wikipedia.org/wiki/Raspberry_Pi ) - tools that people delight in picking up and playing with. So I look more toward [Jupyter]( http://jupyter.org/ ) notebooks and even your [MathCell]( https://paulmasson.github.io/mathcell/ ) as being the webMath efforts of the future that is are viable, shareable project.s

**Comment by paulmasson** [comment]
@theo-armour the state of Rawgit was merely a motivation for the conversation. That issue is easily addressed by switching to jsDelivr, which I have already done for Exploratoria and my other projects and sites.

Whether commit messages are salient or not is not the issue either: this code simply does not work. I cannot be associated with broken code nor can I condone simply leaving it for someone else to address. If you are not going to fix it, are you going to commit to deleting it?

**Comment by theo-armour** [comment]
@paulmasson 

> If you are not going to fix it, are you going to commit to deleting it?

No. I am not a fan of deleting stuff. Even mistakes may serve a purpose.
 
> I cannot be associated with broken code nor can I condone simply leaving it for someone else to address.

I understand. I have removed you as a member of the webMath organization. Is this a sufficient disassociation?

And, fingers crossed that you find a better venue for applying your talents.

**Comment by paulmasson** [comment]
@theo-armour that will do. The same problem exists with respect to the Exploratoria sandbox repository. It too is full of broken code that you presumably will not want to update nor delete. If that is the case, please move it to some other organization in the near future. Since I actively maintain the main Exploratoria repository, please honor this request for the same reasons.

**Comment by paulmasson** [comment]
@theo-armour I asked you to move the sandbox repository because that would be the only way to confirm you had all of your code. Instead you appear to have copied it, so I have no way of confirming if you have it all or not. If you are done with the version in Exploratoria, then please delete it.

**Comment by theo-armour** [comment]
@paulmasson 

Sandbox repository files in exploratoria have been forked successfully. My membership in Exploratoria is terminated. You may proceed as you wish with the repository.
